# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Z3950-ZOOM
version:      1.02
version_from: lib/Net/Z3950/ZOOM.pm
installdirs:  site
requires:
    MARC::Record:                  1.38

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
